services:
  app:
    build: .
    container_name: ops-min-app
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 3000
      DATABASE_URL: file:/app/data/dev.db
      BASIC_AUTH_USER: gyg_user
      BASIC_AUTH_PASS: gyg_pass
      BASIC_AUTH_USER_2: gyg_user_prod
      BASIC_AUTH_PASS_2: gyg_pass_prod
      ADMIN_TOKEN: xuran123
      DEFAULT_SUPPLIER_ID: supplier123
    ports:
      - '3000:3000'
    volumes:
      - ./data:/app/data
